# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  deploy:
    machine:
        enabled: true
    steps:
      - checkout
      - run:
          name: "copy files to web server"
          command: |
            scp -r src/* $USR@$HOST:$(if [ $CIRCLE_BRANCH == "master" ]; then "$WS_FOLDER/"; else "$WS_FOLDER/dev/"; fi)

workflows:
  version: 2
  auto-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
                - development
        

